name: action_cable_stream
version: 0.0.1
description: >-
  ActionCable client port in dart using streams, available in web, dartVM and flutter.
homepage: https://github.com/kwent/actioncable_stream_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.20.0
  web_socket_channel: ^1.1.0
